ru.MyAppName=Сервер баз данных Firebird 1.5
ru.ServerInstall=Полная инсталляция Сервера и инструментов разработки.
ru.SuperServerInstall=Полная инсталляция Супер Сервера и инструментов разработки.
ru.ClassicServerInstall=Полная инсталляция Классика и инструментов разработки.
ru.DeveloperInstall=Установка инструментария клиента для Разработчиков и Администраторов баз данных.
ru.ClientInstall=Минимальная клиентская установка - без сервера и инструментов.
ru.CustomInstall=Установка по выбору
ru.SuperServerComponent=Бинарные файлы Супер Сервера
ru.ClassicServerComponent=Бинарные файлы Классика
ru.ServerComponent=Компоненты Сервера
ru.DevAdminComponent=Инструменты Разработчика и администратора
ru.ClientComponent=Клиентские компоненты
ru.UseGuardianTask=Использовать &Guardian для управления сервером?
ru.UseApplicationTaskMsg=Запускать в качестве &Приложения?
ru.TaskGroupDescription=Запустить сервер Firebird в качестве:
ru.UseServiceTask=Запустить в качестве &Службы?
ru.AutoStartTask=Запускать &Firebird автоматически при каждой загрузке?
ru.CopyFbClientToSysTask=Скопировать клиентскую библиотеку &Firebird в директорий <system>?
ru.CopyFbClientAsGds32Task=Сгенерировать клиентскую библиотеку, как GDS32.DLL для поддержки &унаследованных приложений?
ru.InstallCPLAppletTask="Установить Апплет &Панели Управления?"
ru.instreg=Обновление реестра
ru.instclientCopyFbClient=Копирование fbclient в директорий <sys>
ru.instclientGenGds32=Генерация gds32.dll дли директория <sys>
ru.instclientDecLibCountGds32="Декрементируем счетчик для общей библиотеки gds32 и удаляем его, если необходимо."
ru.instclientDecLibCountFbClient="Декрементируем счетчик для общей библиотеки fbclient и удаляем его, если необходимо."
ru.instsvcSetup=Установка службы
ru.instsvcStartQuestion=Запустить Службу Firebird прямо сейчас?
ru.instsvcStartMsg=Запуск сервера
ru.instsvcStopMsg="Остановка службы "
ru.instsvcRemove="Удаление службы "
ru.instappStartQuestion=Запустить Firebird прямо сейчас?
ru.instappStartMsg=Запуск сервера

ru.InstallSummarySuffix1=Эта версия Firebird выполнит установку по умолчанию.
ru.InstallSummarySuffix2=Обратите внимание, что установка этой версии Firebird,
ru.InstallSummarySuffix3= когда уже установлена более поздняя версия, может привести
ru.InstallSummarySuffix4=                 к не предсказуемым результатам.

ru.InstallSummaryCancel1= Если вы продолжите установку этой версии, Firebird будет установлен, но не будет сконфигурирован.
ru.InstallSummaryCancel2= Вы должны завершить установку в ручную.
ru.InstallSummaryCancel3= Хотите ли вы ПРЕКРАТИТЬ установку?

ru.InstalledProducts= Предварительный анализ показывает, что %s существующий Firebird или Interbase %s был найден.
ru.InstalledProdCountSingular=версия
ru.InstalledProdCountPlural=версии

ru.FbRunning1=В настоящее время есть запущенный Firebird %1 Сервер.
ru.FbRunning2= Вы должны закрыть приложение или остановить
ru.FbRunning3=         службу прежде, чем продолжите.

ru.PreviousInstallBroken=   (Инсталляция не удалась по причине не совпадения строки версии.)
ru.PreviousInstallGood=   (Инсталляция прошла корректно.)

ru.IconReadme=Firebird 1.5 Readme
ru.IconUninstall=Деинсталляция Firebird
ru.ReleaseNotes= release notes. (Требуется Acrobat Reader.)
ru.Uninstall=Деинсталляция Firebird
ru.Winsock2Web1=Не установлен Winsock 2.
ru.Winsock2Web2=Хотите ли вы посетить домашнюю страницу обновления Winsock 2?
ru.NoWinsock2=Пожалуйста, установите обновление Winsock 2 прежде, чем продолжить
ru.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

ru.RunCSNoGuardian=Запуск Классика Firebird (без guardian)
ru.RunSSNoGuardian=Запуск Супер Сервера Firebird (без guardian)
ru.RunSSWithGuardian=Запуск Супер Сервера Firebird (с guardian)
ru.RunCSWithGuardian=Запуст Классика Firebird (с guardian)
ru.RunISQL=Запуск интерактивной утилиты Interactive SQL

ru.ReadmeFile=readme.txt
ru.InstallationReadmeFile=installation_readme.txt

