pt.MyAppName=Servidor SQL Firebird 1.5
pt.SuperServerInstall=Instalação completa do Super Server e ferramentas de desenvolvimento.
pt.ClassicServerInstall=Instalação completa do Classic Server e ferramentas de desenvolvimento.
pt.DeveloperInstall=Instalação das ferramentas do Cliente para programadores e administradores.
pt.ClientInstall=Instalação mínima do Cliente - sem servidor, sem ferramentas.
pt.CustomInstall=Instalação personalizada.
pt.SuperServerComponent=Binários Super Server
pt.ClassicServerComponent=Binários Classic Server
pt.ServerComponent=Componentes do Servidor
pt.DevAdminComponent=Componentes do Programador e das ferramentas de administração
pt.ClientComponent=Componentes do Cliente
pt.UseGuardianTask=Usar o &Guardian para controlar o servidor?
pt.UseApplicationTaskMsg=Executar como &Aplicação?
pt.TaskGroupDescription=Executar o servidor Firebird como:
pt.UseServiceTask=Executar como um &Serviço?
pt.AutoStartTask=Iniciar o &Firebird automaticamente de cada vez que o Windows arranca?
pt.CopyFbClientToSysTask=Copiar a biblioteca do cliente &Firebird para a pasta de <sistema>?
pt.CopyFbClientAsGds32Task=Criar a biblioteca cliente como GDS32.DLL para "retro-compatibilidade"?
pt.InstallCPLAppletTask="Instalar a aplicação no &Painel de Controlo?"
pt.instreg=Modificando o registo
pt.instclientCopyFbClient=Copiando o fbclient para a pasta <sys>
pt.instclientGenGds32=Criando o gds32.dll para a pasta <sys>
pt.instclientDecLibCountGds32="Decrementando o contador de bibliotecas partilhadas para o gds32 e removendo-o se possível."
pt.instclientDecLibCountFbClient="Decrementando o contador de bibliotecas partilhadas para o fbclient e removendo-o se possível."
pt.instsvcSetup=Configurando o serviço
pt.instsvcStartQuestion=Iniciar o Serviço Firebird agora?
pt.instsvcStartMsg=Iniciando o servidor
pt.instsvcStopMsg="Parando o servidor"
pt.instsvcRemove="Removendo o servidor"
pt.instappStartQuestion=Iniciar o Firebird agora?
pt.instappStartMsg=Iniciando o servidor

pt.InstallSummarySuffix1=Esta versão do Firebird tornar-se-á a instalação por omissão.
pt.InstallSummarySuffix2=Todavia, tome atenção pois ao instalar esta versão do Firebird
pt.InstallSummarySuffix3=  quando uma versão anterior já está instalada pode provocar
pt.InstallSummarySuffix4=                  resultados inesperados.

pt.InstallSummaryCancel1= Se continuar com esta instalação o Firebird será instalado mas não configurado.
pt.InstallSummaryCancel2= Terá que completar a instalação manualmente.
pt.InstallSummaryCancel3= Pretende CANCELAR esta instalação?

pt.InstalledProducts='A análise de reinstalação indica que foram encontradas %s instalações Firebird ou Interbase.
pt.InstalledProdCountSingular=versão tem
pt.InstalledProdCountPlural=versões têm

pt.Fb15Running1=Um Servidor Firebird 1.5 anterior já se encontra em execução.
pt.Fb15Running2=     Tem que fechar a aplicação ou parar o serviço
pt.Fb15Running3=                 antes de continuar.

pt.PreviousInstallBroken=   (A Instalação aparenta estar danificada por disparidade no texto da versão.)
pt.PreviousInstallGood=   (A Instalação aparenta estar correcta.)

pt.IconReadme=Firebird 1.5 Read Me
pt.IconUninstall=Uninstall Firebird
pt.ReleaseNotes= release notes. (Requires Acrobat Reader.)
pt.Uninstall=Uninstall Firebird
pt.Winsock2Web1=Winsock 2 is not installed.
pt.Winsock2Web2=Would you like to Visit the Winsock 2 Update Home Page?
pt.NoWinsock2= Please Install Winsock 2 Update before continuing
pt.MSWinsock2Update= http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

pt.RunCSNoGuardian=Run Firebird classic server (without guardian)
pt.RunSSNoGuardian=Run Firebird Superserver (without guardian)
pt.RunSSWithGuardian=Run Firebird Super Server (with guardian)
pt.RunCSWithGuardian=Run Firebird Classic Server (with guardian)
pt.RunISQL=Run command-line based Interactive SQL tool

