# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.
# depends.mak - burp
# Created by 'make depends.mak'
# Created on 1998-11-17
backup.c.o: backu_proto.h
backup.c.o: backup.c.c
backup.c.o: burp.h
backup.c.o: burp_proto.h
backup.c.o: canon_proto.h
backup.c.o: misc_proto.h
backup.c.o: mvol_proto.h
backup.c.o: source/interbase/include/iberror.h
backup.c.o: source/jrd/align.h
backup.c.o: source/jrd/common.h
backup.c.o: source/jrd/dsc.h
backup.c.o: source/jrd/fil.h
backup.c.o: source/jrd/gds.h
backup.c.o: source/jrd/gds_proto.h
backup.c.o: source/jrd/isc.h
backup.c.o: source/jrd/isc_s_proto.h
backup.c.o: source/jrd/pwd.h
backup.c.o: source/jrd/svc.h
backup.c.o: source/jrd/svc_proto.h
backup.c.o: source/jrd/svc_undoc.h
backup.c.o: source/jrd/thd.h
backup.c.o: source/remote/protocol.h
backup.o: backu_proto.h
backup.o: backup.c
backup.o: burp.h
backup.o: burp_proto.h
backup.o: canon_proto.h
backup.o: misc_proto.h
backup.o: mvol_proto.h
backup.o: source/interbase/include/iberror.h
backup.o: source/jrd/align.h
backup.o: source/jrd/common.h
backup.o: source/jrd/dsc.h
backup.o: source/jrd/fil.h
backup.o: source/jrd/gds.h
backup.o: source/jrd/gds_proto.h
backup.o: source/jrd/gdsassert.h
backup.o: source/jrd/isc.h
backup.o: source/jrd/isc_s_proto.h
backup.o: source/jrd/ods.h
backup.o: source/jrd/pwd.h
backup.o: source/jrd/svc.h
backup.o: source/jrd/svc_proto.h
backup.o: source/jrd/svc_undoc.h
backup.o: source/jrd/thd.h
backup.o: source/remote/protocol.h
burp.o: backu_proto.h
burp.o: burp.c
burp.o: burp.h
burp.o: burp_proto.h
burp.o: burpswi.h
burp.o: misc_proto.h
burp.o: mvol_proto.h
burp.o: resto_proto.h
burp.o: source/interbase/include/iberror.h
burp.o: source/jrd/build_no.h
burp.o: source/jrd/common.h
burp.o: source/jrd/dsc.h
burp.o: source/jrd/fil.h
burp.o: source/jrd/gds.h
burp.o: source/jrd/gds_proto.h
burp.o: source/jrd/gdsassert.h
burp.o: source/jrd/ibase.h
burp.o: source/jrd/ibsetjmp.h
burp.o: source/jrd/isc.h
burp.o: source/jrd/isc_s_proto.h
burp.o: source/jrd/license.h
burp.o: source/jrd/msg_encode.h
burp.o: source/jrd/pwd.h
burp.o: source/jrd/svc.h
burp.o: source/jrd/svc_proto.h
burp.o: source/jrd/svc_undoc.h
burp.o: source/jrd/thd.h
burp.o: source/jrd/time.h
burp.o: source/jrd/why_proto.h
burpwep.o: burpwep.c
burpwep.o: source/jrd/common.h
canonical.o: burp.h
canonical.o: burp_proto.h
canonical.o: canon_proto.h
canonical.o: canonical.c
canonical.o: misc_proto.h
canonical.o: source/interbase/include/iberror.h
canonical.o: source/jrd/align.h
canonical.o: source/jrd/common.h
canonical.o: source/jrd/dsc.h
canonical.o: source/jrd/fil.h
canonical.o: source/jrd/gds.h
canonical.o: source/jrd/gds_proto.h
canonical.o: source/jrd/ibsetjmp.h
canonical.o: source/jrd/isc.h
canonical.o: source/jrd/isc_s_proto.h
canonical.o: source/jrd/pwd.h
canonical.o: source/jrd/sdl.h
canonical.o: source/jrd/sdl_proto.h
canonical.o: source/jrd/svc.h
canonical.o: source/jrd/svc_proto.h
canonical.o: source/jrd/svc_undoc.h
canonical.o: source/jrd/thd.h
canonical.o: source/remote/allr_proto.h
canonical.o: source/remote/blk.h
canonical.o: source/remote/protocol.h
canonical.o: source/remote/remote.h
canonical.o: source/remote/remote_def.h
canonical.o: source/remote/xdr.h
gsplit.o: gsplit.c
gsplit.o: gsplit.h
gsplit.o: source/jrd/common.h
misc.o: burp.h
misc.o: burp_proto.h
misc.o: misc.c
misc.o: misc_proto.h
misc.o: source/interbase/include/iberror.h
misc.o: source/jrd/common.h
misc.o: source/jrd/dsc.h
misc.o: source/jrd/fil.h
misc.o: source/jrd/gds.h
misc.o: source/jrd/gds_proto.h
misc.o: source/jrd/isc.h
misc.o: source/jrd/isc_s_proto.h
misc.o: source/jrd/pwd.h
misc.o: source/jrd/svc.h
misc.o: source/jrd/svc_proto.h
misc.o: source/jrd/svc_undoc.h
misc.o: source/jrd/thd.h
mvol.o: burp.h
mvol.o: burp_proto.h
mvol.o: misc_proto.h
mvol.o: mvol.c
mvol.o: mvol_proto.h
mvol.o: source/interbase/include/iberror.h
mvol.o: source/jrd/common.h
mvol.o: source/jrd/dsc.h
mvol.o: source/jrd/fil.h
mvol.o: source/jrd/gds.h
mvol.o: source/jrd/gds_proto.h
mvol.o: source/jrd/gdsassert.h
mvol.o: source/jrd/isc.h
mvol.o: source/jrd/isc_s_proto.h
mvol.o: source/jrd/pwd.h
mvol.o: source/jrd/svc.h
mvol.o: source/jrd/svc_proto.h
mvol.o: source/jrd/svc_undoc.h
mvol.o: source/jrd/thd.h
restore.o: burp.h
restore.o: burp_proto.h
restore.o: canon_proto.h
restore.o: misc_proto.h
restore.o: mvol_proto.h
restore.o: resto_proto.h
restore.o: restore.c
restore.o: source/interbase/include/iberror.h
restore.o: source/intl/charsets.h
restore.o: source/jrd/align.h
restore.o: source/jrd/build_no.h
restore.o: source/jrd/common.h
restore.o: source/jrd/dsc.h
restore.o: source/jrd/fil.h
restore.o: source/jrd/flags.h
restore.o: source/jrd/gds.h
restore.o: source/jrd/gds_proto.h
restore.o: source/jrd/gdsassert.h
restore.o: source/jrd/isc.h
restore.o: source/jrd/isc_s_proto.h
restore.o: source/jrd/license.h
restore.o: source/jrd/obj.h
restore.o: source/jrd/pwd.h
restore.o: source/jrd/svc.h
restore.o: source/jrd/svc_proto.h
restore.o: source/jrd/svc_undoc.h
restore.o: source/jrd/thd.h
restore.o: source/remote/protocol.h
spit.o: burpswi.h
spit.o: source/interbase/include/iberror.h
spit.o: source/jrd/blk.h
spit.o: source/jrd/common.h
spit.o: source/jrd/dsc.h
spit.o: source/jrd/gdsassert.h
spit.o: source/jrd/ibase.h
spit.o: source/jrd/isc.h
spit.o: source/jrd/jrd.h
spit.o: source/jrd/thd.h
spit.o: spit.c
spit.o: spit.h
