pl.MyAppName=Firebird Database Server 2.0
pl.SuperServerInstall=Pe³na instalacja Super Server'a i narzêdzi developera.
pl.ClassicServerInstall=Pe³na instalacja Classic Server'a i narzêdzi developera.
pl.DeveloperInstall=Instalacja narzêdzi klienta dla developerów i administratorów bazy danych.
pl.ClientInstall=MInimalna instalacja klienta - bez serwera, bez narzêdzi.
pl.CustomInstall=DOmyœlna(zwyczajna) instalacja
pl.SuperServerComponent=Super Server binaria
pl.ClassicServerComponent=Classic Server binaria
pl.ServerComponent=Komponenty serwera
pl.DevAdminComponent=Narzêdzia developera i administratora
pl.ClientComponent=Komponenty klienta
pl.UseGuardianTask=U¿ywaæ &Guardian'a do kontrolowania serwera?
pl.UseApplicationTaskMsg=Uruchom jako &Aplikacjê?
pl.TaskGroupDescription=Uruchom Firebird serwer jako:
pl.UseServiceTask=Uruchom jako &Us³ugê?
pl.AutoStartTask=Uruchamiaj &Firebird automatycznie przy ka¿dym starcie systemu?
pl.CopyFbClientToSysTask=Kopiowaæ bibliotekê klienta &Firebird katalogu <system>?
pl.CopyFbClientAsGds32Task=Wygenerowaæ bilbiotê klienta jako GDS32.DLL dla &wsparcia starszych aplikacji?
pl.InstallCPLAppletTask="Zainstalowaæ Control &Panel Applet?"
pl.instreg=Uaktualnienie rejestrów systemu
pl.instclientCopyFbClient=Kopiowanie fbclient to katalogu <sys>
pl.instclientGenGds32=Generowanie gds32.dll dla katalogu <sys>
pl.instclientDecLibCountGds32="Zmniejszenie licznika biblioteki wspó³dzielonej gds32 i usuniêcie jeœli niepotrzebna."
pl.instclientDecLibCountFbClient="Zmniejszenie licznika biblioteki wspó³dzielonej fbclient i usuniêcie jeœli niepotrzebna."
pl.instsvcSetup=Konfigurowanie us³ugi
pl.instsvcStartQuestion=Uruchomiæ teraz us³ugê Firebird'a?
pl.instsvcStartMsg=Uruchamianie serwera
pl.instsvcStopMsg="Zatrzymywanie us³ugi"
pl.instsvcRemove="Usuwanie us³ugi"
pl.instappStartQuestion=Uruchomiæ Firebird'a teraz?
pl.instappStartMsg=Uruchamianie serwera

pl.InstallSummarySuffix1=Ta wersja Firebird'a zostanie domyœln¹ instalacj¹.
pl.InstallSummarySuffix2=WeŸ tak¿e pod uwagê to, ¿e instalowanie tej wersji Firebird'a
pl.InstallSummarySuffix3= kiedy jest ju¿ zainstalowa póŸniejsza wersja mo¿e prowadziæ
pl.InstallSummarySuffix4=                 do nieprzewidzianych rezultatów.

pl.InstallSummaryCancel1= Jeœli kontynuujesz t¹ instalacjê Firebird zostanie zainstalowany ale nie skonfigurowany.
pl.InstallSummaryCancel2= Bêdziesz musia³ dokoñczyæ instalacjê rêcznie.
pl.InstallSummaryCancel3= Czy chcesz PRZERWAÆ instalacjê?

pl.InstalledProducts='re-instalacyjna analiza wykaza³a ¿e istnieje  %s Firebird or Interbase %s been found.
pl.InstalledProdCountSingular=wersja posiada
pl.InstalledProdCountPlural=wersje posiadaj¹

pl.FbRunning1=Istniej¹cy Firebird %1 Server jest uruchomiony.
pl.FbRunning2= Musisz zakoñczyæ program lub zatrzymaæ
pl.FbRunning3=      us³ugê przed kontynuowaniem.

pl.PreviousInstallBroken=   (Instalacja wygl¹da na b³êdna ze wzglêgu na niezgodnoœæ symbolu wersji.)
pl.PreviousInstallGood=   (Instalacja wygl¹da na poprawn¹.)

pl.IconReadme=Firebird 2.0 Readme
pl.IconUninstall=Odinstalowanie Firebird'a
pl.ReleaseNotes= Noty emisyjne. (Wymaga Acrobat Reader.)
pl.Uninstall=Odinstalowanie Firebird'a
pl.Winsock2Web1=Winsock 2 jest niezainstalowy.
pl.Winsock2Web2=Chcesz odwiedziæ Winsock 2 Update Home Page?
pl.NoWinsock2 = Proszê zainstalowaæ Winsock 2 Update zanim kontynuujesz
pl.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

pl.RunCSNoGuardian=Uruchom Firebird classic server (bez guardian'a)
pl.RunSSNoGuardian=Uruchom Firebird Superserver (bez guardian'a)
pl.RunSSWithGuardian=Urumom Firebird Super Server (z guardian'em)
pl.RunCSWithGuardian=Uruchom Firebird Classic Server (z guardian'em)
pl.RunISQL=Uruchom Interactive SQL - narzêdzie lini komend

pl.ReadmeFile=czytajto.txt
pl.InstallationReadmeFile=instalacja_czytajto.txt

