hu.MyAppName=Firebird Adatbázis Szerver 1.5
hu.SuperServerInstall=Teljes telepítése a Szuper Szervernek és fejlesztõi eszközöknek.
hu.ClassicServerInstall=Teljes telepítése a Hagyományos Szervernek és fejlesztõi eszközöknek.
hu.DeveloperInstall=Kliens eszközök telepítése fejlesztõk és adatbázis adminisztrátorok részére.
hu.ClientInstall=Minimális Kliens telepítés - szerver és eszközök nem kerülnek telepítésre.
hu.CustomInstall=Egyedi telepítés
hu.SuperServerComponent=Szuper Szerver futtatható állomány
hu.ClassicServerComponent=Classic Server futtatható állomány
hu.ServerComponent=Szerver komponensek
hu.DevAdminComponent=Fejlesztõi és adminisztrációs eszközök
hu.ClientComponent=Kliens komponensek
hu.UseGuardianTask=Kívánja a &Guardian szolgáltatást használni a szerver irányításához?
hu.UseApplicationTaskMsg=Futtatás &Programként?
hu.TaskGroupDescription=A Firebird szerver futtatása mint:
hu.UseServiceTask=Futtatás &Szervízként?
hu.AutoStartTask=Elinduljon-e a &Firebird automatikusan minden rendszerindításkor?
hu.CopyFbClientToSysTask=Legyen-e egy másolat a &Firebird kliens könyvtárról a <system> mappában?
hu.CopyFbClientAsGds32Task=Létrejöjjön-e a kliens könyvtás GDS32.DLL néven is az ö&rökölt programok támogatására?
hu.InstallCPLAppletTask="Telepíteni kívánja a Firebird &Vezérlõpult Programját?"
hu.instreg=A regisztrációs bejegyzések frissítése
hu.instclientCopyFbClient=Az fbclient.dll másolása a <system> mappába
hu.instclientGenGds32=A gds32.dll létrehozása a <sys> mappában
hu.instclientDecLibCountGds32="A gds32.dll megosztott könyvtár számlálójának csökkentése és a amennyiben lehetséges a fájl eltávolítása."
hu.instclientDecLibCountFbClient="A fbclient.dll megosztott könyvtár számlálójának csökkentése és a amennyiben lehetséges a fájl eltávolítása."
hu.instsvcSetup=A szervíz beállítása
hu.instsvcStartQuestion=Most kívánja elinítani a Firebird Szervízt?
hu.instsvcStartMsg=A szerver elindítása
hu.instsvcStopMsg="A szervíz leállítása"
hu.instsvcRemove="A szervíz eltávolítása"
hu.instappStartQuestion=Most kívánja elinítani a Firebird Szervert?
hu.instappStartMsg=A szerver elindítása

hu.InstallSummarySuffix1=A Firebird ezen verziója lesz az alapértelmezett telepítés.
hu.InstallSummarySuffix2=Továbbá, jegyezze meg, hogy a Firebird ezen verziójának telepítése
hu.InstallSummarySuffix3= a már telepített késöbbi verziókra megjósolhatatlan
hu.InstallSummarySuffix4=                 következményekkel járhat.

hu.InstallSummaryCancel1= Ha folytatja, a Firebird telepítésre kerül, de nem lesz beállítva.
hu.InstallSummaryCancel2= A telepítés tökéletesítését kézzel kell majd elvégeznie.
hu.InstallSummaryCancel3= MÉGSEM helyezi üzembe ezt a telepítést?

hu.InstalledProducts='Az újratelepítési vizsgálat az mutatja, hogy %s létezõ Firebird vagy Interbase %s a számítógépen.
hu.InstalledProdCountSingular=található
hu.InstalledProdCountPlural=találhatóak

hu.Fb15Running1=Egy létezõ Firebird 1.5 Szerver már fut.
hu.Fb15Running2= A folytatás elött Önnek be kell zárnia a futó alkalmazást,
hu.Fb15Running3=          vagy le kell állítani szervízt.

hu.PreviousInstallBroken=   (A telepítés hibásnak tûnik a nem megfelelõ verzó-azonosító miatt.)
hu.PreviousInstallGood=   (A telepítés hibátlannak tûnik.)

hu.IconReadme=Firebird 1.5 Read Me
hu.IconUninstall=Uninstall Firebird
hu.ReleaseNotes= release notes. (Requires Acrobat Reader.)
hu.Uninstall=Uninstall Firebird
hu.Winsock2Web1=Winsock 2 is not installed.
hu.Winsock2Web2=Would you like to Visit the Winsock 2 Update Home Page?
hu.NoWinsock2= Please Install Winsock 2 Update before continuing
hu.MSWinsock2Update= http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

hu.RunCSNoGuardian=Run Firebird classic server (without guardian)
hu.RunSSNoGuardian=Run Firebird Superserver (without guardian)
hu.RunSSWithGuardian=Run Firebird Super Server (with guardian)
hu.RunCSWithGuardian=Run Firebird Classic Server (with guardian)
hu.RunISQL=Run command-line based Interactive SQL tool

