sk.MyAppName=Databázovı server Firebird %1
sk.ServerInstall=Úplná inštalácia Serveru vrátane nástrojov pre správu
sk.SuperServerInstall=Úplná inštalácia Super Serveru vrátane nástrojov pre správu
sk.ClassicServerInstall=Úplná inštalácia Classic Serveru vrátane nástrojov pre správu
sk.DeveloperInstall=Klientská inštalácia vrátane nástrojov pre správu
sk.ClientInstall=Minimálna klientská inštalácia
sk.CustomInstall=Volite¾ná inštalácia
sk.SuperServerComponent=Super Server
sk.ClassicServerComponent=Classic Server
sk.ServerComponent=Databázovı server Firebird
sk.DevAdminComponent=Nástroje pre správu
sk.ClientComponent=Klientská kninica
sk.UseGuardianTask=Poui bezpeèné spustenie pomocou &Guardian?
sk.UseApplicationTaskMsg=Spúša ako samostatnú &aplikáciu?
sk.TaskGroupDescription=Spôsob spúšania Firebird serveru:
sk.UseServiceTask=Spúša ako &slubu?
sk.AutoStartTask=Automaticky spúša pri štarte &poèítaèa?
sk.CopyFbClientToSysTask=Kopírova klientskú kninicu firebirdu do <sys> adresára?
sk.CopyFbClientAsGds32Task=Vytvori klientskú kninicu GDS32.DLL pre podporu starších aplikácií?
sk.InstallCPLAppletTask="Inštalova prídavnı modul do kontrolného panelu?"
sk.instreg=Aktualizácia registra
sk.instclientCopyFbClient=Kopírovanie klientskej kninice do <sys> adresára
sk.instclientGenGds32=Vytváranie gds32.dll v <sys> adresári
sk.instclientDecLibCountGds32="Zníenie poètu instancií pre sdie¾anú kninicu gds32 a jej odstránenie ak je to moné."
sk.instclientDecLibCountFbClient="Zníenie poètu instancií pre sdie¾anú kninicu fbclient a jej odstránenie ak je to moné."
sk.instsvcSetup=Nastavenie sluby
sk.instsvcStartQuestion=Spusti teraz slubu Firebird ?
sk.instsvcStartMsg=Spúšam server
sk.instsvcStopMsg="Zastavujem slubu Firebird"
sk.instsvcRemove="Odstránenie sluby Firebird"
sk.instappStartQuestion=Spusti teraz Firebird ?
sk.instappStartMsg=Spúšam server

sk.InstallSummarySuffix1=Inštalovaná verzia Firebirdu sa nastaví ako vıchodisková.
sk.InstallSummarySuffix2=Upozornenie: Pokraèovanie v inštalácii
sk.InstallSummarySuffix3=môe vies k nepredvídate¾nému chovaniu
sk.InstallSummarySuffix4=ak je na poèítaèi nainštalovaná novšia verzia firebirdu.

sk.InstallSummaryCancel1= Pokraèovaním v inštalácii sa Firebird nainštaluje, ale nenakonfiguruje
sk.InstallSummaryCancel2= a budete musie dokonèi inštaláciu ruène.
sk.InstallSummaryCancel3= Chcete preruši inštaláciu ?

sk.InstalledProducts=Na poèítaèi je u nainštalovanı Firebird %s alebo Interbase %s.
sk.InstalledProdCountSingular=verzia má
sk.InstalledProdCountPlural=verzie majú

sk.FbRunning1=Prvotne inštalovanı %s databázovı server je spustenı.
sk.FbRunning2= Predtım, ne budete pokraèova, 
sk.FbRunning3=        ho musíte zastavi.

sk.PreviousInstallBroken=   (inštalácia zrejme nie je funkèná.)
sk.PreviousInstallGood=   (inštalácia je zrejme funkèná.)

sk.IconReadme=Firebird %1 Readme
sk.IconUninstall=Uninstall Firebird %1
sk.ReleaseNotes= release notes. (Requires Acrobat Reader.)
sk.InstallationGuide= installation guide. (Requires Acrobat Reader.)
sk.BugFixes= bug fixes. (Requires Acrobat Reader.)
sk.Uninstall=Uninstall Firebird %1
sk.Winsock2Web1=Winsock 2 nie je nainštalovanı.
sk.Winsock2Web2=Chcete zobrazi domovskú stránku Winsock 2?
sk.NoWinsock2=Ne budete pokraèova nainštalujte si prosím Winsock 2 Update 
sk.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

sk.RunCSNoGuardian=Spusti Firebird Classic Server (bez strácu)
sk.RunSSNoGuardian=Spusti Firebird Super Server (bez strácu)
sk.RunSSWithGuardian=Spusti Firebird Super Server (so strácom)
sk.RunCSWithGuardian=Spusti Firebird Classic Server (so strácom)
sk.RunISQL=Spusti nástroj príkazového riadku Interactive SQL tool

sk.ReadmeFile=readme.txt
sk.InstallationReadmeFile=installation_readme.txt
