#!/bin/sh

##
# Firebird SQL Database Server
##

. /etc/rc.common

StartService ()
{
    ConsoleMessage "Starting Firebird SQL Database server"
    /Library/Frameworks/Firebird.framework/Resources/bin/fbguard -daemon -forever
}

StopService ()
{
    ConsoleMessage "Stopping Firebird SQL Database server"
    killall fbguard
    killall fbserver
    killall fb_smp_server	
}

RestartService ()
{
    ConsoleMessage "Restarting Firebird SQL Database server"
    killall fbguard
    killall fbserver
    killall fb_smp_server	
    /Library/Frameworks/Firebird.framework/Resources/bin/fbguard -daemon -forever
}

RunService "$1"
