#!/bin/sh

##
# Firebird SQL Database Server
##

. /etc/rc.common

StartService ()
{
    ConsoleMessage "Starting Firebird SQL Database server"
    /Library/Frameworks/Firebird.framework/Resources/bin/fbmgr.bin -start
}

StopService ()
{
    ConsoleMessage "Stopping Firebird SQL Database server"
    /Library/Frameworks/Firebird.framework/Resources/bin/fbmgr.bin -shut -password masterkey
}

RestartService ()
{
    ConsoleMessage "Restarting Firebird SQL Database server"
    /Library/Frameworks/Firebird.framework/Resources/bin/fbmgr.bin -shut -password masterkey
    /Library/Frameworks/Firebird.framework/Resources/bin/fbmgr.bin -start
}

RunService "$1"
