#!/bin/sh
#
# Script args:
# $0: full path to script
# $1: full path to top level package dir, no trailing slash
# $2: full path to installed location
# $3:  ????? Path to install Volume????
# $4:  ?????

FB_FW="/Library/Frameworks/Firebird.framework"

if test -f "$FB_FW/Versions/A/Resources/English.lproj/var/isc4.gdb"; then
	mv -f "$FB_FW/Versions/A/Resources/English.lproj/var/isc4.gdb" /tmp/fb-security-database-update.fdb
fi
if test -f "$FB_FW/Versions/A/Resources/English.lproj/var/isc4.fdb"; then
	mv -f "$FB_FW/Versions/A/Resources/English.lproj/var/isc4.fdb" /tmp/fb-security-database-update.fdb
fi
if test -f "$FB_FW/Versions/A/Resources/English.lproj/var/security.fdb"; then
	mv -f "$FB_FW/Versions/A/Resources/English.lproj/var/security.fdb" /tmp/fb-security-database-update.fdb
fi
if test -f "$FB_FW/Versions/A/Resources/English.lproj/var/security2.fdb"; then
	mv -f "$FB_FW/Versions/A/Resources/English.lproj/var/security2.fdb" /tmp/fb-security-database-update2.fdb
fi
if [ -f /Library/StartupItems/Firebird/Firebird ]; then
	/Library/StartupItems/Firebird/Firebird stop
fi

if [ -f /Library/LaunchDaemons/org.firebird.gds.plist ]; then
	launchctl unload /Library/LaunchDaemons/org.firebird/gds.plist
fi
rm -rf "$FB_FW/Firebird.framework"
rm -rf /Library/StartupItems/Firebird
rm /Library/LaunchDaemons/org.firebird.gds.plist
exit 0
