es.MyAppName=Firebird 2.0
es.SuperServerInstall=Instalación completa de Super Server y herramientas de desarrollo
es.ClassicServerInstall=Instalación completa de Classic Server y herramientas de desarrollo
es.DeveloperInstall=Instalación de herramientas de cliente para desarrolladores y administradores
es.ClientInstall=Instalación mínima de cliente - sin servidor, ni herramientas
es.CustomInstall=Instalación personalizada
es.SuperServerComponent=Ejecutable Super Server
es.ClassicServerComponent=Ejecutable Classic Server
es.ServerComponent=Componentes de Servidor
es.DevAdminComponent=Herramientas de desarrollo y administración
es.ClientComponent=Componentes de cliente
es.UseGuardianTask=¿Usar el &Guardian para controlar el servidor?
es.UseApplicationTaskMsg=¿Ejecutar como una &Aplicación?
es.TaskGroupDescription=Ejecutar el servidor Firebird como:
es.UseServiceTask=¿Ejecutar como un &Servicio?
es.AutoStartTask=¿Arrancar &Firebird automáticamente cada vez que reinicia el sistema?
es.CopyFbClientToSysTask=¿Copiar la librería &cliente de Firebird al directorio <system>?
es.CopyFbClientAsGds32Task=¿Copiar librería cliente como GDS32.DLL para soporte de ap&licaciones antiguas?
es.InstallCPLAppletTask=¿Instalar el Applet del &Panel de Control?
es.instreg=Actualizando el registro
es.instclientCopyFbClient=Copiando fbclient al directorio <sys>
es.instclientGenGds32=Generando gds32.dll en el directorio <sys>
es.instclientDecLibCountGds32=Decrementando el contador de uso de la librería compartida gds32 y eliminándola si corresponde.
es.instclientDecLibCountFbClient=Decrementando el contador de uso de la librería compartida fbclient y eliminándola si corresponde.
es.instsvcSetup=Configurando el servicio
es.instsvcStartQuestion=¿Arrancar el servicio Firebird ahora?
es.instsvcStartMsg=Arrancando el servidor
es.instsvcStopMsg=Deteniendo el servicio
es.instsvcRemove=Eliminando el servicio
es.instappStartQuestion=¿Arrancar Firebird ahora?
es.instappStartMsg=Arrancando el servidor
es.InstallSummarySuffix1=Esta versión de Firebird será la instalación por defecto.
es.InstallSummarySuffix2=Tenga en cuenta que instalar esta versión de Firebird
es.InstallSummarySuffix3= cuando ya hay una versión posterior instalada
es.InstallSummarySuffix4=  puede dar lugar a resultados impredecibles.

es.InstallSummaryCancel1= Si Ud. continúa con la instalación, Firebird se instalará pero no será configurado.
es.InstallSummaryCancel2= Tendrá que completar la instalación manualmente.
es.InstallSummaryCancel3= ¿Desea CANCELAR esta instalación?

es.InstalledProducts='el análisis de re-instalación indica que se ha(n) encontrado %s %s de Firebird o Interbase.'
es.InstalledProdCountSingular=versión
es.InstalledProdCountPlural=versiones

es.FbRunning1=Una versión del servidor Firebird %1 se está ejecutando.
es.FbRunning2=  Debe cerrar esta aplicación o detener el servicio
es.FbRunning3=              antes de continuar.

es.PreviousInstallBroken=   (La instalación parece defectuosa debido a una diferencia en la cadena de versión.)
es.PreviousInstallGood=   (La instalación parece estar correcta.)

es.IconReadme=Leame Firebird 2.0
es.IconUninstall=Desinstalar Firebird
es.ReleaseNotes= notas de versión. (Requiere Acrobat Reader.)
es.Uninstall=Desinstalar Firebird
es.Winsock2Web1=Winsock 2 no está instalado.
es.Winsock2Web2=¿Desea visitar la página de actualización de Winsock 2?
es.NoWinsock2 = Por favor actualice Winsock 2 antes de continuar
es.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

es.RunCSNoGuardian=Ejecutar Firebird Classic server (sin guardian)
es.RunSSNoGuardian=Ejecutar Firebird Superserver (sin guardian)
es.RunSSWithGuardian=Ejecutar Firebird Super Server (con guardian)
es.RunCSWithGuardian=Ejecutar Firebird Classic Server (con guardian)
es.RunISQL=Ejecutar la herramienta SQL interactiva de línea de comandos

es.ReadmeFile=leame.txt
es.InstallationReadmeFile=leame_instalacion.txt
