#!/bin/sh
# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.

# This script makes and populates the mtar directory of a build tree.
# It can be used as part of the process of making either a delivery
# tar file or a package (as for use with Solaris pkgadd command).
# It should normally be run as root, so that the mtar/interbase directory
# and its contents will owned by root.

# Derived from maketar 1997-10-31 by CJewell

if [ -f interbase/bin/ibserver ]; then
    # creating superserver tar file
    echo 'Creating super server archive'

    # copy the required file to mtar directory
    if [ -d mtar ]; then
        # mtar exists delete and remove directory
        rm -rf mtar
    fi
    #create mtar and copy new stuff
    mkdir mtar
    mkdir mtar/interbase
    mkdir mtar/interbase/bin
    mkdir mtar/interbase/doc
    mkdir mtar/interbase/examples
    mkdir mtar/interbase/help
    mkdir mtar/interbase/include
    mkdir mtar/interbase/intl
    mkdir mtar/interbase/lib
    cp interbase/bin/ibserver mtar/interbase/bin/ibserver
    cp interbase/bin/fred mtar/interbase/bin/fred
    cp interbase/bin/gbak mtar/interbase/bin/gbak
    cp interbase/bin/gdef mtar/interbase/bin/gdef
    cp interbase/bin/gds_lock_print mtar/interbase/bin/gds_lock_print
    cp interbase/bin/ibguard mtar/interbase/bin/ibguard
    cp interbase/bin/gfix mtar/interbase/bin/gfix
    cp interbase/bin/gpre mtar/interbase/bin/gpre
    cp interbase/bin/gsec mtar/interbase/bin/gsec
    cp interbase/bin/gsplit mtar/interbase/bin/gsplit
    cp interbase/bin/gstat mtar/interbase/bin/gstat
    cp interbase/bin/ibmgr.bin mtar/interbase/bin/ibmgr.bin
    cp interbase/bin/isc4.gbak mtar/interbase/bin/isc4.gbak
    cp interbase/bin/iblicense mtar/interbase/bin/iblicense
    cp interbase/bin/isql mtar/interbase/bin/isql
    cp interbase/bin/qli mtar/interbase/bin/qli

    cp interbase/doc/* mtar/interbase/doc
    
    cp interbase/examples/v5/* mtar/interbase/examples
    cp -r interbase/help mtar/interbase
    cp -r interbase/include mtar/interbase
    cp interbase/install mtar/interbase/install
    cp -r interbase/intl mtar/interbase
    cp interbase/interbase.msg mtar/interbase/interbase.msg
    cp interbase/isc4.gdb mtar/interbase/isc4.gdb
    cp interbase/isc_config mtar/interbase/isc_config
    cp interbase/isc_ins_hlp.dat mtar/interbase/isc_ins_hlp.dat

    # for SOLARIS 
    if [ -f interbase/lib/gdsmt.so.1 ]; then
         cp interbase/lib/gdsmt.so.1 mtar/interbase/lib/gdsmt.so.0
         ( cd mtar/interbase/lib; ln -s gdsmt.so.0 gds.so.0 )
         TARFLAGS_CREATE="cvpf"
         TARFLAGS_VIEW="tvf"
    fi
    if [ -f interbase/lib/ib_util.so ]; then
    	 cp interbase/lib/ib_util.so mtar/interbase/lib/
    fi
    
    # for HP-UX
    if [ -f interbase/lib/gds.sl.1 ]; then
         cp interbase/lib/gds.sl.1 mtar/interbase/lib/gds.sl
         TARFLAGS_CREATE="cvpf"
         TARFLAGS_VIEW="tvf"
    fi
    if [ -f interbase/lib/ib_util.sl ]; then
    	 cp interbase/lib/ib_util.sl mtar/interbase/lib/
    fi

    cp interbase/lib/gds_pyxis.a mtar/interbase/lib/
    cp interbase/lib/gdsintl mtar/interbase/lib/

    cp interbase/lib/ib_udf mtar/interbase/lib/

    cp interbase/lock_header_template mtar/interbase/lock_header_template
    cp interbase/services.isc mtar/interbase/services.isc
#    cp interbase/README mtar/interbase/README
#    cp interbase/Install_InterBase.txt mtar/interbase/Install_InterBase.txt
    cp interbase/Install_UNIX.txt mtar/interbase/Install_UNIX.txt
    cp interbase/Release_Notes.pdf \
         mtar/interbase/Release_Notes.pdf

else
   echo "This is not a super server kit!!"
fi
