#!/bin/sh
# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.

HOSTNAME=`uname -n`

mv -f /usr/interbase/isc4.gdb /usr/tmp
mv -f /usr/interbase/ib_license.dat /usr/tmp
mv -f /usr/interbase/isc_config /usr/tmp

rm -f /usr/interbase/*.${HOSTNAME}
rm -f /usr/interbase/interbase.log
rm -f /usr/interbase/bin/ibmgr

if [ -h /usr/interbase ]; then
    rm /usr/interbase
fi
exit 0
