#!/bin/sh
# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.
# Shell script to refresh a tree's sources from CVS and run a build.
#
# This script is intended to run by builder (or the other owner of
# the tree being built.  CVSROOT must have been set, and if using the
# "pserver" method of access to cvs, then "cvs login" must have been
# done.
#
cvs update
#
build_kit $(SYSTEM) $(VERSION)
if [ $? = 0 ]; then
    exit 0
else
    exit 1
fi
