#!/bin/sh
# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.

#
# This script creates the shipping directories for SCO UNIX
# It must be run from the top level directory of the kit as
# root.
#
# cd to the kit directory SCO_custom and edit copy_set_prot
# and site_variables and set them to the correct version.
# i.e. the PRODREL variable in site_variables and in the line
# containing the second mcs command in copy_set_prot.  If 
# you are just creating a kit for 3 1/2" floppies, you
# must also comment out the DEVICE variable and uncomment
# the correct floppy drive rfd0135ds18 (floppy 0) or
# rfd1135ds18 (floppy 1).
#
# Run copy_set_prot.  Once the kit is made,
# cd Images/"version" ("version" will be something like V.4.0A)
# ln -s 96ds15 135ds18 (96ds15 = 5 1/4 hd , 135ds18 = 3 1/2 hd)
# cd ../..
#
# run mkflops or mkflops -o (-o invokes floppy drive #1)
#
# Make sure you select the format option in mkflops if the
# floppies have not already been formatted on a SCO box!
#
here=`pwd`
mkdir SCO_custom
chmod 700 SCO_custom
cd SCO_custom
mkdir source
chmod 700 source
cp $here/SCO/original/site_variables .
cp $here/SCO/original/copy_set_prot .
chmod 700 site_variables copy_set_prot
cd source
mkdir tmp usr
chmod 700 tmp usr
cd tmp
cp $here/SCO/original/init.intrbase .
chmod 700 init.intrbase
mkdir perms
chmod 700 perms
cd perms
cp $here/SCO/original/prep.intrbase .
chmod 700 prep.intrbase
cd ../../usr
mkdir lib
chmod 700 lib
cd lib
mkdir custom
chmod 700 custom
cd custom
cp $here/SCO/original/intrbase.rmv .
chmod 700 intrbase.rmv
