#!/bin/sh
# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.
# Shell script to copy physical databases into directories
# instead of having links to the databases
#
cp journal/journal.gdb temporary.gdb
rm journal/journal.gdb
mv temporary.gdb journal/journal.gdb
chmod 666 journal/journal.gdb
#
cp journal/journal_vms.gdb temporary.gdb
rm journal/journal_vms.gdb
mv temporary.gdb journal/journal_vms.gdb
chmod 666 journal/journal_vms.gdb
#
cp jrd/yachts.gdb temporary.gdb
rm jrd/yachts.gdb
mv temporary.gdb jrd/yachts.gdb
chmod 666 jrd/yachts.gdb
#
cp jrd/isc.gdb temporary.gdb
rm jrd/isc.gdb
mv temporary.gdb jrd/isc.gdb
chmod 666 jrd/isc.gdb
#
cp msgs/master_msg_db temporary.gdb
rm msgs/master_msg_db
mv temporary.gdb msgs/master_msg_db
chmod 666 msgs/master_msg_db
#
cp pyxis/forms.gdb temporary.gdb
rm pyxis/forms.gdb
mv temporary.gdb pyxis/forms.gdb
chmod 666 pyxis/forms.gdb
#
cp qli/help.gdb temporary.gdb
rm qli/help.gdb
mv temporary.gdb qli/help.gdb
chmod 666 qli/help.gdb
#
cp utilities/rebuild.gdb temporary.gdb
rm utilities/rebuild.gdb
mv temporary.gdb utilities/rebuild.gdb
chmod 666 utilities/rebuild.gdb
#
cp example4/empbuild.gdb temporary.gdb
rm example4/empbuild.gdb
mv temporary.gdb example4/empbuild.gdb
chmod 666 example4/empbuild.gdb
#
cp example5/empbuild.gdb temporary.gdb
rm example5/empbuild.gdb
mv temporary.gdb example5/empbuild.gdb
chmod 666 example5/empbuild.gdb
#
cp examples/atlas.gdb temporary.gdb
rm examples/atlas.gdb
mv temporary.gdb examples/atlas.gdb
chmod 666 examples/atlas.gdb
#
cp examples/c_guide.gdb temporary.gdb
rm examples/c_guide.gdb
mv temporary.gdb examples/c_guide.gdb
chmod 666 examples/c_guide.gdb
#
cp examples/emp.gdb temporary.gdb
rm examples/emp.gdb
mv temporary.gdb examples/emp.gdb
chmod 666 examples/emp.gdb
#
cp examples/nc_guide.gdb temporary.gdb
rm examples/nc_guide.gdb
mv temporary.gdb examples/nc_guide.gdb
chmod 666 examples/nc_guide.gdb
#
cp examples/slides.gdb temporary.gdb
rm examples/slides.gdb
mv temporary.gdb examples/slides.gdb
chmod 666 examples/slides.gdb
#
cp examples/stocks.gdb temporary.gdb
rm examples/stocks.gdb
mv temporary.gdb examples/stocks.gdb
chmod 666 examples/stocks.gdb
#
echo 'Removing marion.gdb.  Use gbak to create a new one.'
rm marion.gdb
