/*
  FILE GENERATED BY src/misc/writeBuildNum.sh 
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:834 
*/

#define PRODUCT_VER_STRING "1.5.0.834"
#define FILE_VER_STRING "WI-T1.5.0.834"
#define LICENSE_VER_STRING "WI-T1.5.0.834"
#define FILE_VER_NUMBER 1, 5, 0, 834
#define FB_MAJOR_VER "1"
#define FB_MINOR_VER "5"
#define FB_REV_NO "0"
#define FB_BUILD_NO "834"
#define FB_BUILD_TYPE "T"
#define FB_BUILD_SUFFIX "Firebird 1.5 Alpha 1"
